version: "3.9"

services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: docker/
      dockerfile: nginx.dockerfile
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/laravel-react-shop
    networks:
      - app-network
    depends_on:
      - fpm
  fpm:
    container_name: fpm
    restart: always
    build:
      context: docker/
      dockerfile: fpm.dockerfile
    volumes:
      - ./:/var/www/laravel-react-shop
    networks:
      - app-network
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    restart: always
    image: mysql:8.0
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
    dbdata: