version: "3.3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    ports:
      - 8080:80
    links:
      - fpm
    volumes:
      - ./:/var/www/laravel-react-shop/backend
  fpm:
    build:
      context: .
      dockerfile: docker/fpm.dockerfile
    volumes:
      - ./:/var/www/laravel-react-shop/backend
    links:
      - mysql
  mysql:
    image: mysql:8.0
    ports:
      - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel